### ISSUE TITLE
Mesh-Issue

### ISSUE THREAD

**Issue by Reichi95** [pierre-picard/minibot#19]
Hey, wondering if this is finally the right place for Mesh-Issue-Reports(?).

So i've linked a youtube video to the Mesh issue in the Tanaan Jungle (WoD-Intro) of the Dark Portal.
Navigation on the whole Portal is impossible. The Meshed area is under the Dark portal Object, if you're on the platform and stairs no meshes are loading at all? So hopefully that's all the Information you need. If not, let me know what to add for this report and the next :-)

https://www.youtube.com/watch?v=1MidUXAfhM0&feature=youtu.be

//EDIT: I'd try to do it by myself, but i had no success in getting the Map extractor/editor whatever working.. So i can't do it on my own. (Maybe you can provide a Useable Ready version for retarded people like me to download & use?)

**Comment by pierre-picard** [comment]
Hi,

We don't have the capability to test this atm, but we believe this is a huge game object refreshed from server. Such objects are not possible to be included in mesh since it is not static.

You can verify this by turning on ESP feature with "game object" selected, and you may be able to see it. Let me know the result.

Thanks for your report.

**Comment by pierre-picard** [comment]
Just confirmed this structure is a game object via secondary engine ESP. Its ID is 237670. So it cannot be meshed.
