### ISSUE TITLE
high performance drop when using an addon

### ISSUE THREAD

**Issue by buloti** [pierre-picard/minibot#2]
I am running WoW + minibot on a VM (GPU passtrough) without any problem I put a FPS cap at 50.
But when I start to use an addon based on Minibot unlocked feature the fps drop from 50 (cap) to 3-20 depending of the number of monsters and maybe other things. When i rest or in ghost form the fps are back to 50.

**Comment by buloti** [comment]
tested different addons of the same type. got the same problem on all of them. They all use meshes, rotations, loot etc.

**Comment by pierre-picard** [comment]
1. Because these AddOns are not written from scratch based on our API. I believe they are just ported from EWT and not optimized for MiniBot. The API is a lot different so you will for sure get this.
2. Our project framework contains two modules written in Lua as well. Check how they perform without any FPS loss.
3. I will not monitor here and not on duty for any support. Join the channel for general support like this.
