### ISSUE TITLE
drawline

### ISSUE THREAD

**Issue by Mrasd741** [pierre-picard/minibot#24]
Is there a drawline function？，i don‘t find api

**Comment by fusspawn** [comment]
Only via something like Libdraw. There's no hardware accelerated drawline.

**Comment by Mrasd741** [comment]
I'm sorry for my stupid problem because I don't understand the underlying implementation, i want to a  function like ewt（ LibDraw.Circle(x, y, z, r)）

**Comment by fusspawn** [comment]
https://gist.github.com/benphelps/7f88f181978267edf899  lib draw is just a
lua library. You can include it in your project.

Be aware you need to make changes to world to screen to make it work with
minibot.

@pierre-picard a real hardware accelerated (direct x) Drawing that isn't
slow would be a welcome addition to minibot.

**Comment by Mrasd741** [comment]
thank you so much

**Comment by Mrasd741** [comment]
i save LibDraw in  /interface folder , add 
 《LibDraw.Sync(function()
-- You have access to the following draw methods (in 3D or world space).

 --  LibDraw.Draw2DLine(1, 100, 200, 300)
   LibDraw.Circle(posX, posY, posZ, 10)

end)
LibDraw.Enable(0.1)
》
 in  my  script 。
but  it’s invalid ，Can you give me some advice？
you say ” make some change to world  “ ， What is the exact meaning of this ？

**Comment by Mrasd741** [comment]
i use 5 hour ， i find LibDraw Default compatible FireHack , i Modify worldtoscreen() return  and  some  code    i find LibDraw.Draw2DLine() can‘t work    ， maybe     L:SetPoint("TOPRIGHT", LibDraw.canvas, "TOPLEFT", sx, sy)
    L:SetPoint("BOTTOMLEFT", LibDraw.canvas, "TOPLEFT", ex, ey)  can't work  。
i am Very distressed。 if you have LibDraw’s   Available versions，Can you share it with me？

**Comment by pierre-picard** [comment]
This issue is not sth worth the hard work as:

1. WoW has built-in Line rendering via https://wowpedia.fandom.com/wiki/Widget_API#Line. This belongs to the WoW UI rendering system and can enjoy the whole bunch of benefits such as UI scaling and interaction events. And it is internally well optimized as a matter of fact as we should trust BLZ developers are no worse than us.
2. We would have to re-invent all wheels should we go this way, which is long and valueless. The first stumbling block would be DX11 & DX12 compatibility which is proven to be hard, followed by many DirectX reset issues when users change their UI settings.
